// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.kafka.code.model.proto;

public interface kafkaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kafka.code.model.model.kafkaResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 error_code = 1;</code>
   */
  int getErrorCode();

  /**
   * <code>optional string error_message = 2;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>optional string error_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>optional int32 order_value = 3;</code>
   */
  int getOrderValue();
}
