// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.kafka.code.model.proto;

public interface kafkaRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kafka.code.model.model.kafkaRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 price = 1;</code>
   */
  int getPrice();

  /**
   * <code>optional int32 qty = 2;</code>
   */
  int getQty();

  /**
   * <code>optional string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
