// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.kafka.code.model.proto;

public final class KafkaBasicsProto {
  private KafkaBasicsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kafka_code_model_model_kafkaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kafka_code_model_model_kafkaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kafka_code_model_model_kafkaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kafka_code_model_model_kafkaResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrequest.proto\022\032com.kafka.code.model.mo" +
      "del\"8\n\014kafkaRequest\022\r\n\005price\030\001 \001(\005\022\013\n\003qt" +
      "y\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\"O\n\rkafkaResponse\022\022" +
      "\n\nerror_code\030\001 \001(\005\022\025\n\rerror_message\030\002 \001(" +
      "\t\022\023\n\013order_value\030\003 \001(\005B0\n\032com.kafka.code" +
      ".model.protoB\020KafkaBasicsProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_kafka_code_model_model_kafkaRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kafka_code_model_model_kafkaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kafka_code_model_model_kafkaRequest_descriptor,
        new java.lang.String[] { "Price", "Qty", "Name", });
    internal_static_com_kafka_code_model_model_kafkaResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_kafka_code_model_model_kafkaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kafka_code_model_model_kafkaResponse_descriptor,
        new java.lang.String[] { "ErrorCode", "ErrorMessage", "OrderValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
